// [V24] 翰林題庫
window.levelData_level6_hanlin = {
    // --- 請將您 words.js 中 level6_hanlin: {...} 裡的所有 "年級物件" 貼在這裡 ---
    
    // 七年級上學期
    grade_7A: {
        單元1: [
                { word: 'handsome', translation: '英俊的', sentence_en: 'Brian: Your father is handsome.', sentence_zh: '布萊恩：你的父親很英俊。' },
                { word: 'new', translation: '新的', sentence_en: 'Anna: Thank you. Ryan: Is your new school bag cool?', sentence_zh: '安娜：謝謝你。雷恩：你的新書包酷嗎？' },
                { word: 'classmate', translation: '同學', sentence_en: 'Katie: That\'s Zoe. She\'s my classmate.', sentence_zh: '凱蒂：那位是柔依。她是我的同學。' },
                { word: 'young', translation: '年輕的', sentence_en: 'Tony: Our new teacher is 24 years old. Leah: He\'s young.', sentence_zh: '東尼：我們的新老師 24 歲。莉亞：他很年輕。' },
                { word: 'woman', translation: '女人', sentence_en: 'Who\'s that beautiful tall woman?', sentence_zh: '那位美麗的高個子女人是誰？' },
                { word: 'very', translation: '非常', sentence_en: 'This tree is very tall.', sentence_zh: '這棵樹非常高。' },
                { word: 'beautiful', translation: '美麗的', sentence_en: 'Your school is big and beautiful.', sentence_zh: '你的學校又大又美麗。' },
                { word: 'too', translation: '太 (過分)', sentence_en: 'Gigi: My dad is a teacher, too.', sentence_zh: '吉吉：我爸爸也是老師。' },
                { word: 'nice', translation: '美好的/親切的', sentence_en: 'Mandy: Nice to meet you, Mr. Brown.', sentence_zh: '曼蒂：很高興見到你，布朗先生。' },
                { word: 'meet', translation: '遇見', sentence_en: 'Nice to meet you, too.', sentence_zh: '很高興見到你。' },
                { word: 'cousin', translation: '表(堂)兄弟姊妹', sentence_en: 'Roy: I\'m from Mill Junior High School. Zoe: Oh, really? I am, too.', sentence_zh: '羅伊：我來自米爾國中。柔依：哦，真的嗎？我也是。' },
                { word: 'really', translation: '真的', sentence_en: 'I really like this book.', sentence_zh: '我真的很喜歡這本書。' },
                { word: 'year(s) old', translation: '歲', sentence_en: 'Her son is 17 years old.', sentence_zh: '她的兒子 17 歲了。' },
                { word: 'see', translation: '看見', sentence_en: 'I see it. I see.', sentence_zh: '我看到了。' },
                { word: 'singer', translation: '歌手', sentence_en: 'Fred: Who\'s the man in this picture? Kate: He\'s a singer.', sentence_zh: '弗雷德：圖片中這個男人是誰？凱特：他是個歌手。' },
                { word: 'officer', translation: '警官', sentence_en: 'This is my cousin, a police officer.', sentence_zh: '這是我表哥，一名警官。' },
                { word: 'housewife', translation: '家庭主婦', sentence_en: 'My grandmother is a housewife.', sentence_zh: '我的祖母是個家庭主婦。' },
                { word: 'writer', translation: '作家', sentence_en: 'Are you a writer?', sentence_zh: '你是個作家嗎？' },
                { word: 'uncle', translation: '叔叔/伯伯', sentence_en: 'My uncle is a good cook.', sentence_zh: '我的叔叔是個好廚師。' },
                { word: 'aunt', translation: '阿姨/姑姑', sentence_en: 'Aunt Shelly is my mother\'s good friend.', sentence_zh: '雪莉阿姨是我媽媽的好朋友。' },
                { word: 'wife', translation: '妻子', sentence_en: 'Isn\'t his wife a doctor?', sentence_zh: '他的妻子難道不是醫生嗎？' },
                { word: 'daughter', translation: '女兒', sentence_en: 'Julia is Mr. and Mrs. Wilson\'s daughter.', sentence_zh: '茱莉亞是威爾森夫婦的女兒。' },
                { word: 'husband', translation: '丈夫', sentence_en: 'Her husband is a nurse.', sentence_zh: '她的丈夫是個護士。' },
                { word: 'son', translation: '兒子', sentence_en: 'Mrs. Fang is a mother of three sons.', sentence_zh: '方太太是三個兒子的母親。' },
                { word: 'dear', translation: '親愛的', sentence_en: 'This is a picture of my dear students.', sentence_zh: '這是我的親愛的學生們的照片。' },
                { word: 'family', translation: '家人', sentence_en: 'How\'s your family?', sentence_zh: '你的家人怎麼樣？' },
                { word: 'elementary school', translation: '小學', sentence_en: 'My daughter is young. She is an elementary school student.', sentence_zh: '我的女兒很年輕，她是一名小學生。' },
                { word: 'junior high school', translation: '國中', sentence_en: 'Their mom is a junior high school teacher.', sentence_zh: '他們的媽媽是個國中老師。' },
                { word: 'baby', translation: '嬰兒', sentence_en: 'The baby\'s father is Mr. Martin.', sentence_zh: '這個嬰兒的爸爸是馬丁先生。' }
        ],
        單元2: [
                { word: 'house', translation: '房子', sentence_en: 'Jimmy is not in the house.', sentence_zh: 'Jimmy 不在房子裡。' },
                { word: 'parents', translation: '父母親', sentence_en: 'Her parents are very nice.', sentence_zh: '她的父母親人很好。' },
                { word: 'wall', translation: '牆壁', sentence_en: 'The walls of this room are thin.', sentence_zh: '這個房間的牆很薄。' },
                { word: 'living room', translation: '客廳', sentence_en: 'The new sofa is in the living room.', sentence_zh: '新沙發在客廳裡。' },
                { word: 'purple', translation: '紫色的／紫色', sentence_en: 'The singer\'s hair is purple.', sentence_zh: '那位歌手的頭髮是紫色的。' },
                { word: 'special', translation: '特別的', sentence_en: 'What\'s special about this pencil?', sentence_zh: '這枝鉛筆有什麼特別的？' },
                { word: 'favorite', translation: '最喜愛的／最愛', sentence_en: 'This is my favorite park. It\'s nice and big.', sentence_zh: '這是我最喜歡的公園，很漂亮也很大。' },
                { word: 'color', translation: '顏色', sentence_en: 'My favorite color is blue.', sentence_zh: '我最喜歡的顏色是藍色。' },
                { word: 'kitchen', translation: '廚房', sentence_en: 'Is your aunt in the kitchen?', sentence_zh: '你阿姨在廚房嗎？' },
                { word: 'bedroom', translation: '臥室', sentence_en: 'Her bedroom is next to the living room.', sentence_zh: '她的臥室在客廳旁邊。' },
                { word: 'but', translation: '但是', sentence_en: 'My room is big, but my bed is not.', sentence_zh: '我的房間很大，但我的床不是。' },
                { word: 'gray', translation: '灰色的／灰色', sentence_en: 'My dad\'s car is gray.', sentence_zh: '我爸爸的車是灰色的。' },
                { word: 'brown', translation: '棕色的／棕色', sentence_en: 'Jerry\'s dog is brown.', sentence_zh: 'Jerry 的狗是棕色的。' },
                { word: 'cookie', translation: '餅乾', sentence_en: 'They are cookies for my mom.', sentence_zh: '那些是給我媽媽的餅乾。' },
                { word: 'mice', translation: '老鼠(mouse 的複數)', sentence_en: 'Two white mice are in the box.', sentence_zh: '盒子裡有兩隻白色老鼠。' },
                { word: 'maybe', translation: '也許；可能', sentence_en: 'Maybe he\'s in his dog house.', sentence_zh: '也許他在他的狗屋裡。' },
                { word: 'behind', translation: '在⋯後面', sentence_en: 'Look! Kenny\'s cat is behind the tree.', sentence_zh: '你看!Kenny 的貓在樹後面。' },
                { word: 'hungry', translation: '飢餓的', sentence_en: 'I\'m hungry.', sentence_zh: '我肚子餓了。' },
                { word: 'notebook', translation: '筆記本', sentence_en: 'My notebooks are in my schoolbag.', sentence_zh: '我的筆記本在我的書包裡。' },
                { word: 'marker', translation: '記號筆；彩色筆', sentence_en: 'Where is my pink marker? It\'s under your desk.', sentence_zh: '我的粉紅色彩色筆在哪裡？它在你的桌子下。' },
                { word: 'brush', translation: '毛筆；畫刷', sentence_en: 'Your brush is under your bed.', sentence_zh: '你的畫筆在你的床底下。' },
                { word: 'gift', translation: '禮物', sentence_en: 'It\'s a gift for you.', sentence_zh: '這是一份給你的禮物。' },
                { word: 'pencil case', translation: '鉛筆盒', sentence_en: 'My pencil case is on the desk.', sentence_zh: '我的鉛筆盒在桌上。' },
                { word: 'bathroom', translation: '浴室；廁所', sentence_en: 'Are you in the bathroom, Mom?', sentence_zh: '媽媽，你在浴室嗎？' },
                { word: 'dining room', translation: '飯廳', sentence_en: 'Aren\'t the eggs on the dining room table?', sentence_zh: '那些蛋不是在飯廳的桌上嗎？' },
                { word: 'table', translation: '桌子', sentence_en: 'Your pencil is on the table.', sentence_zh: '你的鉛筆在桌上。' },
                { word: 'sofa', translation: '沙發', sentence_en: 'The old sofa is in my grandfather\'s bedroom.', sentence_zh: '那張舊沙發在我祖父的臥室裡。' },
                { word: 'near', translation: '在⋯附近', sentence_en: 'My uncle\'s farm is near the zoo.', sentence_zh: '我叔叔的農場在動物園附近。' },
                { word: 'between', translation: '在⋯之間', sentence_en: 'Who is that between your mom and dad? She\'s my sister, Nina.', sentence_zh: '你爸爸媽媽中間那位是誰？她是我妹妹 Nina。' },
                { word: 'in front of', translation: '在⋯前面', sentence_en: 'The old tree is in front of our school.', sentence_zh: '那棵老樹在我們學校前面。' },
                { word: 'inside', translation: '在⋯裡面', sentence_en: 'What\'s inside the box?', sentence_zh: '盒子裡有什麼？' },
                { word: 'right', translation: '就；正好', sentence_en: 'My house is right next to a park.', sentence_zh: '我家就緊鄰著一座公園。' },
                { word: 'each other', translation: '彼此；互相', sentence_en: 'My classmates are nice to each other.', sentence_zh: '我的同學彼此都很好。' },
                { word: 'above', translation: '在⋯上方；在上方', sentence_en: 'The clock is above the TV.', sentence_zh: '時鐘在電視上方。' },
                { word: 'person', translation: '人', sentence_en: 'Jeremy is a nice person.', sentence_zh: 'Jeremy 是個好人。' }
        ],
            單元3: [
                { word: 'guy', translation: '人；傢伙', sentence_en: 'Guys, don\'t run in the classroom.', sentence_zh: '各位同學，別在教室裡跑。' },
                { word: 'with', translation: '和；與', sentence_en: 'She\'s in the car with Dad.', sentence_zh: '她和爸爸在車上。' },
                { word: 'can', translation: '可以；會', sentence_en: 'We can\'t eat in the lab.', sentence_zh: '我們不能在實驗室吃東西。' },
                { word: 'many', translation: '許多（的）', sentence_en: 'Many English teachers are women.', sentence_zh: '許多英文老師是女性。' },
                { word: 'place', translation: '地方', sentence_en: 'What is this place? It\'s beautiful.', sentence_zh: '這是什麼地方？這裡很漂亮。' },
                { word: 'use', translation: '使用', sentence_en: 'Can I use the bathroom?', sentence_zh: '我可以用一下浴室嗎？' },
                { word: 'sure', translation: '當然；確定的', sentence_en: 'I\'m not sure.', sentence_zh: '我不太確定。' },
                { word: 'let\'s', translation: '讓我們一起⋯', sentence_en: 'Let\'s watch TV now.', sentence_zh: '我們現在來看電視吧。' },
                { word: 'careful', translation: '小心的', sentence_en: 'Hey, be careful.', sentence_zh: '嘿，小心。' },
                { word: 'museum', translation: '博物館', sentence_en: 'Please don\'t run in the museum.', sentence_zh: '請不要在博物館裡跑步。' },
                { word: 'Hurry!', translation: '快點！', sentence_en: 'Hurry up, Sandy!', sentence_zh: '快一點，Sandy!' },
                { word: 'please', translation: '請', sentence_en: 'Please close the door for me.', sentence_zh: '請幫我把門關上。' },
                { word: 'wait', translation: '等待', sentence_en: 'Please wait.', sentence_zh: '請稍候。' },
                { word: 'man', translation: '男人；男子', sentence_en: 'That man is my uncle. He\'s a doctor.', sentence_zh: '那位男子是我叔叔，他是醫生。' },
                { word: 'now', translation: '現在', sentence_en: 'Freddy is in the bathroom now.', sentence_zh: 'Freddy 現在在浴室裡。' },
                { word: 'or', translation: '或者；或', sentence_en: 'Don\'t eat or drink on the bus.', sentence_zh: '在公車上不要吃東西或喝飲料。' },
                { word: 'time', translation: '次；時間', sentence_en: 'Please be careful this time.', sentence_zh: '這次請小心一點。' },
                { word: 'wake up', translation: '喚醒；叫醒；醒來', sentence_en: 'Can you wake your sister up?', sentence_zh: '你可以把你妹妹叫醒嗎？' },
                { word: 'class', translation: '課；班級', sentence_en: 'Please follow class rules.', sentence_zh: '請遵守課堂規則。' },
                //（課本藍框：實用語）
                { word: 'Oh my!', translation: '天啊！', sentence_en: 'Oh my! It\'s a mummy.', sentence_zh: '天啊！是一具木乃伊。' },
                { word: 'see', translation: '看見', sentence_en: 'Can you see the bird in the tree?', sentence_zh: '你看得到樹上的那隻鳥嗎？' },
                { word: 'quiet', translation: '安靜的', sentence_en: 'Ken is a quiet student.', sentence_zh: 'Ken 是個安靜的學生。' },
                { word: 'turn off', translation: '關掉', sentence_en: 'Turn off the TV and go to bed now.', sentence_zh: '把電視關掉，現在去睡覺。' },
                { word: 'sign', translation: '標誌；告示牌', sentence_en: 'Look at the sign. You can\'t eat here.', sentence_zh: '看那個標誌。你不能在這裡吃東西。' },
                { word: 'talk', translation: '說話', sentence_en: 'Let\'s not talk here.', sentence_zh: '我們別在這裡說話。' },
                { word: 'fight', translation: '吵架；打架', sentence_en: 'Don\'t fight with your brother.', sentence_zh: '不要和你哥哥吵架。' },
                { word: 'turn', translation: '（依次輪到的）機會', sentence_en: 'Is it my turn?', sentence_zh: '輪到我了嗎？' },
                // Reading
                { word: 'check', translation: '檢查；核對', sentence_en: 'I\'m not sure. Let me check.', sentence_zh: '我不確定。讓我查一下。' },
                { word: 'wash', translation: '洗；清洗', sentence_en: 'We can wash your dad\'s car this afternoon.', sentence_zh: '我們今天下午可以洗你爸爸的車。' },
                { word: 'after class', translation: '下課後', sentence_en: 'Let\'s play basketball after class.', sentence_zh: '我們下課後打籃球吧。' },
                { word: 'follow', translation: '遵守；跟隨', sentence_en: 'Please follow the museum rules and be good.', sentence_zh: '請遵守博物館規則，做個好孩子。' },
                { word: 'rule', translation: '規則', sentence_en: 'Don\'t use your phone in class. It\'s a classroom rule.', sentence_zh: '上課不要用手機。那是教室規則。' },
                { word: 'safe', translation: '安全的', sentence_en: 'Do not run in the lab. That\'s not safe.', sentence_zh: '不要在實驗室裡跑步。那樣不安全。' }
            ],
            單元4: [
                { word: 'music video', translation: '音樂影片', sentence_en: 'I am watching Mayday\'s new music video.', sentence_zh: '我正在看五月天的新音樂影片。' },
                { word: 'band', translation: '樂團', sentence_en: 'My favorite band is singing on stage.', sentence_zh: '我最喜歡的樂團正在台上演唱。' },
                { word: 'take a look', translation: '看一看', sentence_en: 'Come take a look.', sentence_zh: '過來看一看。' },
                { word: 'cute', translation: '可愛的', sentence_en: 'Toto is a really cute dog.', sentence_zh: 'Toto 是一隻很可愛的狗。' },
                { word: 'great', translation: '棒的；極好的', sentence_en: 'That\'s great!', sentence_zh: '那太棒了！' },
                { word: 'free', translation: '有空的', sentence_en: 'Are you free for the meet-and-greet on Sunday?', sentence_zh: '你星期天有空參加見面會嗎？' },
                { word: 'weekend', translation: '週末', sentence_en: 'The baseball game is this weekend.', sentence_zh: '這週末有一場棒球比賽。' },
                { word: 'Saturday', translation: '星期六', sentence_en: 'The welcome party is on Saturday night.', sentence_zh: '迎新派對在星期六晚上。' },
                { word: 'ready', translation: '準備好的', sentence_en: 'Are you ready for school?', sentence_zh: '你準備好上學了嗎？' },
                { word: 'p.m.', translation: '下午；晚上', sentence_en: 'It\'s 8:25 p.m. now.', sentence_zh: '現在是晚上 8 點 25 分。' },
                { word: 'o\'clock', translation: '…點鐘', sentence_en: 'Can you wake me up at three o\'clock in the afternoon?', sentence_zh: '你可以下午三點叫我起床嗎？' },
                { word: 'day', translation: '日；天', sentence_en: 'It\'s a great day today.', sentence_zh: '今天是很棒的一天。' },
                { word: 'today', translation: '今天', sentence_en: 'It\'s Teacher\'s Day today.', sentence_zh: '今天是教師節。' },
                { word: 'Friday', translation: '星期五', sentence_en: 'It\'s Friday.', sentence_zh: '今天是星期五。' },
                { word: 'Sunday', translation: '星期日', sentence_en: 'The zoo is not open on Sundays.', sentence_zh: '動物園星期日不開放。' },
                { word: 'Monday', translation: '星期一', sentence_en: 'The music class is on Monday afternoon.', sentence_zh: '音樂課在星期一下午。' },
                { word: 'Tuesday', translation: '星期二', sentence_en: 'Can I go to your house on Tuesday?', sentence_zh: '我星期二可以去你家嗎？' },
                { word: 'Wednesday', translation: '星期三', sentence_en: 'Brenda is free this Wednesday.', sentence_zh: 'Brenda 這個星期三有空。' },
                { word: 'Thursday', translation: '星期四', sentence_en: 'Thursday is between Wednesday and Friday.', sentence_zh: '星期四在星期三與星期五之間。' },
                { word: 'week', translation: '週；星期', sentence_en: 'The new museum is open this week.', sentence_zh: '新的博物館本週開放。' },
                { word: 'a.m.', translation: '上午；凌晨', sentence_en: 'Isn\'t the basketball game at 10:50 a.m.?', sentence_zh: '籃球比賽不是在早上 10:50 嗎？' },
                { word: 'study', translation: '研讀；學習', sentence_en: 'Peter is studying in his room.', sentence_zh: 'Peter 正在他的房間裡讀書。' },
                { word: 'English', translation: '英文', sentence_en: 'Mr. Cheng is my English teacher.', sentence_zh: '鄭先生是我的英文老師。' },
                { word: 'take a walk', translation: '散步', sentence_en: 'Let\'s take a walk together.', sentence_zh: '我們一起去散步吧。' },
                { word: 'movie', translation: '電影', sentence_en: 'Is the new movie good?', sentence_zh: '那部新電影好看嗎？' },
                { word: 'take a picture', translation: '拍照', sentence_en: 'Everyone is taking a picture with his or her favorite teacher.', sentence_zh: '大家正在和自己最喜歡的老師合照。' },
                { word: 'party', translation: '派對；宴會', sentence_en: 'I\'m at Timothy\'s party.', sentence_zh: '我在 Timothy 的派對上。' },
                { word: 'report', translation: '報導', sentence_en: 'The woman on TV is reporting from the singer\'s new house.', sentence_zh: '電視上的那位女士正在歌手的新家現場報導。' },
                { word: 'popular', translation: '受歡迎的', sentence_en: 'The singer is very handsome and popular.', sentence_zh: '那位歌手很帥也很受歡迎。' },
                { word: 'fan', translation: '迷；粉絲', sentence_en: 'The fan is taking a picture with the writer.', sentence_zh: '那位粉絲正在和作家合照。' },
                { word: 'shake hands', translation: '握手', sentence_en: 'James is shaking hands with his teacher.', sentence_zh: 'James 正在和他的老師握手。' },
                { word: 'everyone', translation: '每個人；大家', sentence_en: 'The drinks are not enough for everyone.', sentence_zh: '飲料不夠每個人喝。' },
                { word: 'sign', translation: '簽名', sentence_en: 'Can you sign this picture for me?', sentence_zh: '可以幫我在這張照片上簽名嗎？' }
            ],
            單元5: [
                { word: 'date', translation: '日期', sentence_en: 'The date of the concert is September twenty-first.', sentence_zh: '音樂會的日期是九月二十一日。' },
                { word: 'November', translation: '十一月', sentence_en: 'Thanksgiving is in November.', sentence_zh: '感恩節在十一月。' },
                { word: 'first', translation: '第一（的）', sentence_en: 'Sunday is the first day of the week.', sentence_zh: '星期天是一週的第一天。' },
                { word: 'Thanksgiving', translation: '感恩節', sentence_en: 'People can have a day off on Thanksgiving in the USA.', sentence_zh: '在美國，感恩節可以放一天假。' },
                { word: 'important', translation: '重要的', sentence_en: 'Basketball is important to Jesse.', sentence_zh: '對 Jesse 而言，籃球很重要。' },
                { word: 'holiday', translation: '節日；假日', sentence_en: 'Christmas is my favorite holiday.', sentence_zh: '聖誕節是我最喜歡的節日。' },
                { word: 'when', translation: '何時', sentence_en: 'When is their meet-and-greet?', sentence_zh: '他們的見面會是什麼時候？' },
                { word: 'fourth', translation: '第四（的）', sentence_en: 'The fourth class today is English.', sentence_zh: '今天第四節是英文課。' },
                { word: 'birthday', translation: '生日', sentence_en: 'Tomorrow is my birthday.', sentence_zh: '明天是我的生日。' },
                { word: 'also', translation: '也；此外', sentence_en: 'Ted is my cousin, and he\'s also my classmate.', sentence_zh: 'Ted 是我表親，他也是我的同學。' },
                { word: 'before', translation: '在⋯之前', sentence_en: 'Let\'s play a game before dinner.', sentence_zh: '晚餐前我們來玩個遊戲吧。' },
                { word: 'around', translation: '圍繞；在⋯附近', sentence_en: 'Are there many houses around the park?', sentence_zh: '公園周圍有很多房子嗎？' },
                { word: 'How about...?', translation: '那⋯呢？', sentence_en: 'How about you, Lauren?', sentence_zh: '那妳呢，Lauren？' },
                { word: 'second', translation: '第二（的）', sentence_en: 'Rose is Mr. Bean\'s second daughter.', sentence_zh: 'Rose 是 Bean 先生的二女兒。' },
                { word: 'next', translation: '下一個的', sentence_en: 'Christmas Eve is next week.', sentence_zh: '平安夜在下週。' },
                { word: 'month', translation: '月份', sentence_en: 'My sister is seven months old.', sentence_zh: '我妹妹七個月大。' },
                { word: 'January', translation: '一月', sentence_en: 'January is the first month of the year.', sentence_zh: '一月是一年的第一個月。' },
                { word: 'February', translation: '二月', sentence_en: 'The holiday is in February.', sentence_zh: '這個假日在二月。' },
                { word: 'March', translation: '三月', sentence_en: 'The baseball game is on March fifteenth.', sentence_zh: '棒球比賽在三月十五日。' },
                { word: 'April', translation: '四月', sentence_en: 'April is between March and May.', sentence_zh: '四月在三月與五月之間。' },
                { word: 'May', translation: '五月', sentence_en: 'Mother\'s Day is on the second Sunday of May.', sentence_zh: '母親節在五月的第二個星期天。' },
                { word: 'June', translation: '六月', sentence_en: 'June first is on Saturday this year.', sentence_zh: '今年六月一日是星期六。' },
                { word: 'July', translation: '七月', sentence_en: 'July fourth is a very important day in the USA.', sentence_zh: '七月四日是美國很重要的日子。' },
                { word: 'August', translation: '八月', sentence_en: 'Father\'s Day in Taiwan is on August eighth.', sentence_zh: '台灣的父親節在八月八日。' },
                { word: 'September', translation: '九月', sentence_en: 'September twenty-eighth is Confucius\' birthday.', sentence_zh: '九月二十八日是孔子誕辰。' },
                { word: 'October', translation: '十月', sentence_en: 'October is after September.', sentence_zh: '十月在九月之後。' },
                { word: 'December', translation: '十二月', sentence_en: 'Next December I\'m going to the USA with my friends.', sentence_zh: '明年十二月我要和朋友去美國。' },
                { word: 'New Year\'s Eve', translation: '元旦前夕', sentence_en: 'New Year\'s Eve is on December 31.', sentence_zh: '跨年夜是在十二月三十一日。' },
                { word: 'Christmas', translation: '聖誕節', sentence_en: 'It\'s Christmas today.', sentence_zh: '今天是聖誕節。' },
                { word: 'third', translation: '第三（的）', sentence_en: 'March is the third month of the year.', sentence_zh: '三月是一年的第三個月。' },
                { word: 'animal', translation: '動物', sentence_en: 'What\'s your favorite animal?', sentence_zh: '你最喜歡的動物是什麼？' },
                { word: 'cow', translation: '牛；乳牛', sentence_en: 'Don\'t touch the cow. It\'s eating.', sentence_zh: '別碰那頭牛。牠正在吃東西。' },
                { word: 'lucky', translation: '幸運的', sentence_en: 'Twelve is my lucky number.', sentence_zh: '十二是我的幸運數字。' },
                { word: 'only', translation: '只是；唯一的', sentence_en: 'He is only a boy, not a man.', sentence_zh: '他只是個男孩，不是大人。' }
            ],
            單元6: [
                { word: 'lion', translation: '獅子', sentence_en: 'Is there a lion under the tree?', sentence_zh: '樹下有獅子嗎？' },
                { word: 'over there', translation: '在那裡', sentence_en: 'The woman over there is a cook.', sentence_zh: '那邊的那位女士是一位廚師。' },
                { word: 'king', translation: '國王', sentence_en: 'The beautiful house is for the king.', sentence_zh: '那棟漂亮的房子是給國王的。' },
                { word: 'some', translation: '一些（的）', sentence_en: 'There are some comic books on the desk.', sentence_zh: '桌上有一些漫畫書。' },
                { word: 'elephant', translation: '大象', sentence_en: "There's an elephant in front of the bus.", sentence_zh: '公車前面有一隻大象。' },
                { word: 'so', translation: '如此地', sentence_en: "Uncle Peter's farm is so big.", sentence_zh: '彼得叔叔的農場好大。' },
                { word: 'any', translation: '任何（的）', sentence_en: "There aren't any chairs in the classroom.", sentence_zh: '教室裡沒有任何椅子。' },
                { word: 'tiger', translation: '老虎', sentence_en: 'Lions and tigers are big cats.', sentence_zh: '獅子和老虎是大型貓科動物。' },
                { word: 'zebra', translation: '斑馬', sentence_en: 'There are no zebras near here.', sentence_zh: '這附近沒有斑馬。' },
                { word: 'back', translation: '背；後面', sentence_en: "Is that a bird on the dog's back?", sentence_zh: '那是狗背上的一隻鳥嗎？' },
                { word: 'help', translation: '幫助；幫忙', sentence_en: 'The watch is a great help to me.', sentence_zh: '這只手錶對我幫助很大。' },
                { word: 'right', translation: '正確的', sentence_en: "That's right.", sentence_zh: '沒錯。' },
                { word: 'monkey', translation: '猴子', sentence_en: 'There are three monkeys in the tree.', sentence_zh: '樹上有三隻猴子。' },
                { word: 'fox', translation: '狐狸', sentence_en: 'Are there two foxes over there?', sentence_zh: '那邊有兩隻狐狸嗎？' },
                { word: 'horse', translation: '馬', sentence_en: 'This horse is very old.', sentence_zh: '這匹馬很老。' },
                { word: 'rat', translation: '老鼠', sentence_en: 'There is a big rat in the kitchen.', sentence_zh: '廚房裡有一隻大老鼠。' },
                { word: 'bear', translation: '熊', sentence_en: 'Are there any bears in Africa?', sentence_zh: '非洲有熊嗎？' },
                { word: 'world', translation: '世界', sentence_en: 'The lion is the king of the animal world.', sentence_zh: '獅子是動物世界的國王。' },
                { word: 'example', translation: '實例；例子', sentence_en: 'The Lins are a great example of a happy family.', sentence_zh: '林家是一個幸福家庭的好例子。' },
                { word: 'bug', translation: '蟲子', sentence_en: 'Look! There is a bug hiding behind the pencil box.', sentence_zh: '看！鉛筆盒後面藏著一隻蟲。' },
                { word: 'food', translation: '食物', sentence_en: "I\'m hungry. Let's eat some food.", sentence_zh: '我肚子餓了。我們吃點東西吧。' },
                { word: 'clean up', translation: '清理；打掃', sentence_en: 'Tom is cleaning up his room.', sentence_zh: 'Tom 正在打掃他的房間。' },
                { word: 'full', translation: '飽的；滿的', sentence_en: "Are you hungry? — No. I'm full.", sentence_zh: '你餓了嗎？— 不，我吃飽了。' },
                { word: 'healthy', translation: '健康的', sentence_en: "Mary's daughter is a healthy girl.", sentence_zh: '瑪麗的女兒很健康。' },
                { word: 'thanks to', translation: '幸虧；由於', sentence_en: 'Thanks to Mom, we can have a great dinner.', sentence_zh: '多虧了媽媽，我們可以吃到豐盛的晚餐。' },
                { word: 'clean', translation: '乾淨的', sentence_en: 'Their house is very clean.', sentence_zh: '他們的房子很乾淨。' }
            ], 
            Review: [
                { word: 'I think so.', translation: '我也是這麼認為。', sentence_en: 'Is this a good idea? I think so.', sentence_zh: '這個主意不錯嗎？我也這麼想。' },
                { word: 'crack', translation: '裂縫；裂開', sentence_en: 'There is a crack in the wall.', sentence_zh: '牆上有一道裂縫。' },
                { word: 'enough', translation: '足夠的', sentence_en: 'There are enough chairs for everyone.', sentence_zh: '椅子足夠每個人使用。' },
                { word: 'magic', translation: '神奇的；魔法', sentence_en: 'The story is full of magic.', sentence_zh: '這個故事充滿魔法。' },
                { word: 'mummy', translation: '木乃伊', sentence_en: 'We saw a mummy in the museum.', sentence_zh: '我們在博物館看到一具木乃伊。' },
                { word: 'rock', translation: '石塊', sentence_en: 'Don\'t sit on that rock.', sentence_zh: '不要坐在那塊石頭上。' },
                { word: 'dinosaur', translation: '恐龍', sentence_en: 'This book is about dinosaurs.', sentence_zh: '這本書是在講恐龍的。' },
                { word: 'carefully', translation: '小心地', sentence_en: 'Please cross the road carefully.', sentence_zh: '過馬路請小心。' },
                { word: 'lab', translation: '實驗室', sentence_en: 'We have science class in the lab.', sentence_zh: '我們在實驗室上自然課。' },
                { word: 'test tube', translation: '試管', sentence_en: 'Put the water into the test tube.', sentence_zh: '把水倒進試管裡。' },
                { word: 'K-pop', translation: '韓國流行音樂(Korean popular music)', sentence_en: 'My sister loves K-pop.', sentence_zh: '我妹妹很喜歡韓流音樂。' },
                { word: 'all', translation: '所有的', sentence_en: 'All the students are here.', sentence_zh: '所有學生都到齊了。' },
                { word: 'concert', translation: '音樂會；演唱會', sentence_en: 'We are going to the concert tonight.', sentence_zh: '我們今晚要去聽演唱會。' },
                { word: 'together', translation: '一起地', sentence_en: 'Let\'s sing together.', sentence_zh: '我們一起唱歌吧。' },
                { word: 'meet-and-greet', translation: '見面會', sentence_en: 'The meet-and-greet starts at six.', sentence_zh: '見面會六點開始。' },
                { word: 'stage', translation: '舞台', sentence_en: 'The band is on the stage now.', sentence_zh: '樂團現在在舞台上。' },
                { word: 'give', translation: '給', sentence_en: 'Please give me a minute.', sentence_zh: '請給我一分鐘。' },
                { word: 'thankful', translation: '感謝的', sentence_en: 'We are thankful for your help.', sentence_zh: '我們感謝你的幫忙。' },
                { word: 'turkey leg', translation: '火雞腿', sentence_en: 'He eats a big turkey leg on Thanksgiving.', sentence_zh: '他在感恩節吃一支很大的火雞腿。' },
                { word: 'nervous', translation: '緊張的', sentence_en: 'I am nervous before the test.', sentence_zh: '考試前我很緊張。' },
                { word: 'hide', translation: '躲；藏', sentence_en: 'Let\'s hide behind the door.', sentence_zh: '我們躲在門後面吧。' },
                { word: 'mud', translation: '泥巴', sentence_en: 'Don\'t step in the mud.', sentence_zh: '不要踩到泥巴裡。' },
                { word: 'cry out', translation: '喊叫', sentence_en: 'The boy cried out for help.', sentence_zh: '那個男孩大喊求救。' },
                { word: 'Thank goodness!', translation: '謝天謝地！', sentence_en: 'The cat is safe. Thank goodness!', sentence_zh: '貓平安無事，謝天謝地！' },
                { word: 'dinner', translation: '晚餐', sentence_en: 'What do we have for dinner?', sentence_zh: '晚餐我們吃什麼？' },
                { word: 'never', translation: '從不', sentence_en: 'He never eats breakfast.', sentence_zh: '他從不吃早餐。' },
                { word: 'herd', translation: '獸群；群', sentence_en: 'A herd of cows is on the hill.', sentence_zh: '山坡上有一群乳牛。' },
                { word: 'know', translation: '知道', sentence_en: 'Do you know the answer?', sentence_zh: '你知道答案嗎？' },
                { word: 'oxpecker', translation: '牛椋鳥', sentence_en: 'An oxpecker sits on the zebra.', sentence_zh: '一隻牛椋鳥停在斑馬身上。' },
                { word: 'expert', translation: '專家', sentence_en: 'She is an animal expert.', sentence_zh: '她是動物專家。' },
                { word: 'coat', translation: '毛皮；外套', sentence_en: 'The bear has a thick coat.', sentence_zh: '那隻熊有厚厚的毛皮。' },
                { word: 'luckily', translation: '幸運地', sentence_en: 'Luckily, no one was hurt.', sentence_zh: '幸運地，沒有人受傷。' },
                { word: 'provide', translation: '提供', sentence_en: 'Trees provide food for many animals.', sentence_zh: '樹木為許多動物提供食物。' }
            ]
    }, 
    
    // 預留其他年級學期的空間 (目前為空)
    grade_7B: {
        // ... 如果您未來有 7B 的資料，請貼在這裡 ...
    }, 
    grade_8A: {},
    grade_8B: {},
    rade_9A: {}, // [V24 - 提示] 您原始檔案這裡有個錯字， 'g'rade_9A
    grade_9B: {}
};