// 這是 'words.js' 檔案
// 它只包含 'baseWords' 這個變數，裡面有 500+ 個單字

const baseWords = [
    { word: 'apple', translation: '蘋果', sentence_en: 'An apple a day keeps the doctor away.', sentence_zh: '一天一蘋果，醫生遠離我。' },
    { word: 'ant', translation: '螞蟻', sentence_en: 'An ant is a very small insect.', sentence_zh: '螞蟻是一種非常小的昆蟲。' },
    { word: 'arm', translation: '手臂', sentence_en: 'He broke his arm playing basketball.', sentence_zh: '他打籃球時摔斷了手臂。' },
    { word: 'baby', translation: '嬰兒', sentence_en: 'The baby is sleeping.', sentence_zh: '寶寶正在睡覺。' },
    { word: 'bag', translation: '袋子', sentence_en: 'My bag is heavy.', sentence_zh: '我的袋子很重。' },
    { word: 'ball', translation: '球', sentence_en: 'Let\'s play ball!', sentence_zh: '我們來打球吧！' },
    { word: 'banana', translation: '香蕉', sentence_en: 'Monkeys love bananas.', sentence_zh: '猴子喜歡香蕉。' },
    { word: 'bed', translation: '床', sentence_en: 'It\'s time to go to bed.', sentence_zh: '該上床睡覺了。' },
    { word: 'bee', translation: '蜜蜂', sentence_en: 'A bee makes honey.', sentence_zh: '蜜蜂製造蜂蜜。' },
    { word: 'bird', translation: '鳥', sentence_en: 'That bird can sing beautifully.', sentence_zh: '那隻鳥唱得很美。' },
    { word: 'book', translation: '書', sentence_en: 'I am reading a good book.', sentence_zh: '我正在讀一本好書。' },
    { word: 'box', translation: '盒子', sentence_en: 'What\'s in the box?', sentence_zh: '盒子裡是什麼？' },
    { word: 'boy', translation: '男孩', sentence_en: 'The boy is running.', sentence_zh: '那個男孩在跑步。' },
    { word: 'bread', translation: '麵包', sentence_en: 'I eat bread for breakfast.', sentence_zh: '我早餐吃麵包。' },
    { word: 'bus', translation: '公車', sentence_en: 'We take the bus to school.', sentence_zh: '我們搭公車上學。' },
    { word: 'cake', translation: '蛋糕', sentence_en: 'Happy birthday! Let\'s eat cake.', sentence_zh: '生日快樂！我們來吃蛋糕吧。' },
    { word: 'cap', translation: '帽子', sentence_en: 'He wears a blue cap.', sentence_zh: '他戴著一頂藍色帽子。' },
    { word: 'car', translation: '汽車', sentence_en: 'My dad drives a red car.', sentence_zh: '我爸爸開一輛紅色汽車。' },
    { word: 'cat', translation: '貓', sentence_en: 'The cat is chasing a mouse.', sentence_zh: '貓正在追老鼠。' },
    { word: 'chair', translation: '椅子', sentence_en: 'Please sit on the chair.', sentence_zh: '請坐在椅子上。' },
    { word: 'cup', translation: '杯子', sentence_en: 'I want a cup of tea.', sentence_zh: '我想要一杯茶。' },
    { word: 'day', translation: '白天/天', sentence_en: 'Today is a sunny day.', sentence_zh: '今天是個晴天。' },
    { word: 'desk', translation: '書桌', sentence_en: 'My book is on the desk.', sentence_zh: '我的書在書桌上。' },
    { word: 'dog', translation: '狗', sentence_en: 'The dog is barking.', sentence_zh: '狗在吠。' },
    { word: 'doll', translation: '洋娃娃', sentence_en: 'She has many dolls.', sentence_zh: '她有很多洋娃娃。' },
    { word: 'door', translation: '門', sentence_en: 'Please close the door.', sentence_zh: '請關門。' },
    { word: 'duck', translation: '鴨子', sentence_en: 'The duck is swimming in the pond.', sentence_zh: '鴨子在池塘裡游泳。' },
    { word: 'egg', translation: '蛋', sentence_en: 'I had an egg for breakfast.', sentence_zh: '我早餐吃了一顆蛋。' },
    { word: 'eye', translation: '眼睛', sentence_en: 'Close your eyes and sleep.', sentence_zh: '閉上眼睛睡覺。' },
    { word: 'face', translation: '臉', sentence_en: 'Wash your face.', sentence_zh: '洗臉。' },
    { word: 'fish', translation: '魚', sentence_en: 'There are many fish in the river.', sentence_zh: '河裡有很多魚。' },
    { word: 'flower', translation: '花', sentence_en: 'This flower smells good.', sentence_zh: '這朵花聞起來很香。' },
    { word: 'food', translation: '食物', sentence_en: 'What is your favorite food?', sentence_zh: '你最喜歡的食物是什麼？' },
    { word: 'foot', translation: '腳', sentence_en: 'My feet are cold.', sentence_zh: '我的腳很冷。' },
    { word: 'girl', translation: '女孩', sentence_en: 'That girl is my sister.', sentence_zh: '那個女孩是我的妹妹。' },
    { word: 'hand', translation: '手', sentence_en: 'Wash your hands before eating.', sentence_zh: '飯前洗手。' },
    { word: 'head', translation: '頭', sentence_en: 'He nodded his head.', sentence_zh: '他點了點頭。' },
    { word: 'home', translation: '家', sentence_en: 'Let\'s go home.', sentence_zh: '我們回家吧。' },
    { word: 'house', translation: '房子', sentence_en: 'We live in a small house.', sentence_zh: '我們住在一棟小房子裡。' },
    { word: 'key', translation: '鑰匙', sentence_en: 'I lost my key.', sentence_zh: '我弄丟了我的鑰匙。' },
    { word: 'leg', translation: '腿', sentence_en: 'He hurt his leg.', sentence_zh: '他傷了腿。' },
    { word: 'map', translation: '地圖', sentence_en: 'Look at the map.', sentence_zh: '看這張地圖。' },
    { word: 'milk', translation: '牛奶', sentence_en: 'I drink milk every morning.', sentence_zh: '我每天早上喝牛奶。' },
    { word: 'money', translation: '錢', sentence_en: 'He has no money.', sentence_zh: '他沒有錢。' },
    { word: 'moon', translation: '月亮', sentence_en: 'The moon is bright tonight.', sentence_zh: '今晚的月亮很亮。' },
    { word: 'morning', translation: '早上', sentence_en: 'Good morning!', sentence_zh: '早安！' },
    { word: 'name', translation: '名字', sentence_en: 'What\'s your name?', sentence_zh: '你叫什麼名字？' },
    { word: 'nest', translation: '鳥巢', sentence_en: 'The bird is in its nest.', sentence_zh: '鳥在牠的巢裡。' },
    { word: 'night', translation: '晚上', sentence_en: 'Good night, sleep well.', sentence_zh: '晚安，祝你好眠。' },
    { word: 'nose', translation: '鼻子', sentence_en: 'He has a big nose.', sentence_zh: '他有個大鼻子。' },
    { word: 'pen', translation: '筆', sentence_en: 'May I borrow your pen?', sentence_zh: '我可以跟你借筆嗎？' },
    { word: 'pencil', translation: '鉛筆', sentence_en: 'I need a pencil and paper.', sentence_zh: '我需要一支鉛筆和紙。' },
    { word: 'pig', translation: '豬', sentence_en: 'A pig likes to play in the mud.', sentence_zh: '豬喜歡在泥巴里玩。' },
    { word: 'plane', translation: '飛機', sentence_en: 'The plane is flying high.', sentence_zh: '飛機飛得很高。' },
    { word: 'rice', translation: '米飯', sentence_en: 'Do you eat rice every day?', sentence_zh: '你每天都吃米飯嗎？' },
    { word: 'school', translation: '學校', sentence_en: 'Children go to school.', sentence_zh: '孩子們去上學。' },
    { word: 'ship', translation: '船', sentence_en: 'The ship is sailing on the sea.', sentence_zh: '船在海上航行。' },
    { word: 'shoe', translation: '鞋子', sentence_en: 'I have new shoes.', sentence_zh: '我有一雙新鞋。' },
    { word: 'shop', translation: '商店', sentence_en: 'Let\'s go to the shop.', sentence_zh: '我們去那家商店吧。' },
    { word: 'song', translation: '歌曲', sentence_en: 'She is singing a beautiful song.', sentence_zh: '她正在唱一首優美的歌。' },
    { word: 'star', translation: '星星', sentence_en: 'I see a star in the sky.', sentence_zh: '我看到天空中有一顆星星。' },
    { word: 'sun', translation: '太陽', sentence_en: 'The sun is shining.', sentence_zh: '陽光普照。' },
    { word: 'table', translation: '桌子', sentence_en: 'The cat is on the table.', sentence_zh: '貓在桌子上。' },
    { word: 'tea', translation: '茶', sentence_en: 'He is drinking tea.', sentence_zh: '他正在喝茶。' },
    { word: 'time', translation: '時間', sentence_en: 'What time is it?', sentence_zh: '現在幾點了？' },
    { word: 'toy', translation: '玩具', sentence_en: 'The boy is playing with his toy.', sentence_zh: '男孩在玩他的玩具。' },
    { word: 'train', translation: '火車', sentence_en: 'The train is coming.', sentence_zh: '火車來了。' },
    { word: 'tree', translation: '樹', sentence_en: 'That is a big tree.', sentence_zh: '那是一棵大樹。' },
    { word: 'water', translation: '水', sentence_en: 'Please give me some water.', sentence_zh: '請給我一些水。' },
    { word: 'window', translation: '窗戶', sentence_en: 'Open the window, please.', sentence_zh: '請打開窗戶。' },
    { word: 'woman', translation: '女人', sentence_en: 'That woman is my teacher.', sentence_zh: '那位女士是我的老師。' },
    { word: 'world', translation: '世界', sentence_en: 'I want to travel the world.', sentence_zh: '我想環遊世界。' },
    { word: 'zoo', translation: '動物園', sentence_en: 'We saw lions at the zoo.', sentence_zh: '我們在動物園看到獅子。' },
    { word: 'ask', translation: '問', sentence_en: 'Don\'t be afraid to ask questions.', sentence_zh: '不要害怕提問。' },
    { word: 'can', translation: '能/會', sentence_en: 'I can swim.', sentence_zh: '我會游泳。' },
    { word: 'come', translation: '來', sentence_en: 'Please come here.', sentence_zh: '請來這裡。' },
    { word: 'do', translation: '做', sentence_en: 'What are you doing?', sentence_zh: '你正在做什麼？' },
    { word: 'drink', translation: '喝', sentence_en: 'I am thirsty and want to drink water.', sentence_zh: '我渴了，想喝水。' },
    { word: 'eat', translation: '吃', sentence_en: 'It\'s time to eat dinner.', sentence_zh: '該吃晚餐了。' },
    { word: 'fly', translation: '飛', sentence_en: 'Birds can fly.', sentence_zh: '鳥會飛。' },
    { word: 'get', translation: '得到', sentence_en: 'I get good grades.', sentence_zh: '我獲得好成績。' },
    { word: 'give', translation: '給', sentence_en: 'Please give me the book.', sentence_zh: '請把書給我。' },
    { word: 'go', translation: '去', sentence_en: 'Let\'s go to the park.', sentence_zh: '我們去公園吧。' },
    { word: 'have', translation: '有', sentence_en: 'I have a brother.', sentence_zh: '我有一個兄弟。' },
    { word: 'help', translation: '幫忙', sentence_en: 'Can you help me?', sentence_zh: '你能幫我嗎？' },
    { word: 'jump', translation: '跳', sentence_en: 'The frog can jump high.', sentence_zh: '青蛙可以跳得很高。' },
    { word: 'know', translation: '知道', sentence_en: 'I know the answer.', sentence_zh: '我知道答案。' },
    { word: 'like', translation: '喜歡', sentence_en: 'I like apples.', sentence_zh: '我喜歡蘋果。' },
    { word: 'listen', translation: '聽', sentence_en: 'Listen to the music.', sentence_zh: '聽音樂。' },
    { word: 'live', translation: '居住', sentence_en: 'Where do you live?', sentence_zh: '你住在哪裡？' },
    { word: 'look', translation: '看', sentence_en: 'Look at the beautiful flower.', sentence_zh: '看那朵美麗的花。' },
    { word: 'love', translation: '愛', sentence_en: 'I love my family.', sentence_zh: '我愛我的家人。' },
    { word: 'make', translation: '製作', sentence_en: 'Let\'s make a cake.', sentence_zh: '我們來做個蛋糕吧。' },
    { word: 'open', translation: '打開', sentence_en: 'Open your book.', sentence_zh: '打開你的書。' },
    { word: 'play', translation: '玩', sentence_en: 'Children like to play games.', sentence_zh: '孩子們喜歡玩遊戲。' },
    { word: 'put', translation: '放', sentence_en: 'Put the book on the desk.', sentence_zh: '把書放在桌上。' },
    { word: 'read', translation: '閱讀', sentence_en: 'He likes to read books.', sentence_zh: '他喜歡讀書。' },
    { word: 'ride', translation: '騎', sentence_en: 'I can ride a bike.', sentence_zh: '我會騎自行車。' },
    { word: 'run', translation: '跑', sentence_en: 'The dog is running fast.', sentence_zh: '狗跑得很快。' },
    { word: 'say', translation: '說', sentence_en: 'What did you say?', sentence_zh: '你說什麼？' },
    { word: 'see', translation: '看見', sentence_en: 'I see a bird.', sentence_zh: '我看見一隻鳥。' },
    { word: 'sing', translation: '唱歌', sentence_en: 'She likes to sing.', sentence_zh: '她喜歡唱歌。' },
    { word: 'sit', translation: '坐', sentence_en: 'Please sit down.', sentence_zh: '請坐下。' },
    { word: 'sleep', translation: '睡覺', sentence_en: 'The cat is sleeping.', sentence_zh: '貓在睡覺。' },
    { word: 'speak', translation: '說(語言)', sentence_en: 'I can speak English.', sentence_zh: '我會說英語。' },
    { word: 'stand', translation: '站立', sentence_en: 'Please stand up.', sentence_zh: '請起立。' },
    { word: 'study', translation: '學習', sentence_en: 'I study English every day.', sentence_zh: '我每天學習英語。' },
    { word: 'swim', translation: '游泳', sentence_en: 'Fish can swim.', sentence_zh: '魚會游泳。' },
    { word: 'take', translation: '拿', sentence_en: 'Take your umbrella.', sentence_zh: '帶著你的傘。' },
    { word: 'talk', translation: '說話', sentence_en: 'They are talking.', sentence_zh: '他們在說話。' },
    { word: 'teach', translation: '教', sentence_en: 'My mom teaches English.', sentence_zh: '我媽媽教英語。' },
    { word: 'tell', translation: '告訴', sentence_en: 'Tell me a story.', sentence_zh: '告訴我一個故事。' },
    { word: 'think', translation: '想', sentence_en: 'What do you think?', sentence_zh: '你怎麼想？' },
    { word: 'use', translation: '使用', sentence_en: 'Can I use your pen?', sentence_zh: '我可以用你的筆嗎？' },
    { word: 'walk', translation: '走路', sentence_en: 'I walk to school.', sentence_zh: '我走路去上學。' },
    { word: 'want', translation: '想要', sentence_en: 'I want a new toy.', sentence_zh: '我想要一個新玩具。' },
    { word: 'watch', translation: '看(電視)', sentence_en: 'I watch TV every night.', sentence_zh: '我每晚都看電視。' },
    { word: 'work', translation: '工作', sentence_en: 'My father works in a factory.', sentence_zh: '我父親在一家工廠工作。' },
    { word: 'write', translation: '寫', sentence_en: 'Please write your name.', sentence_zh: '請寫下你的名字。' },
    { word: 'bad', translation: '壞的', sentence_en: 'That is a bad idea.', sentence_zh: '那真是個壞主意。' },
    { word: 'big', translation: '大的', sentence_en: 'An elephant is big.', sentence_zh: '大象很大。' },
    { word: 'black', translation: '黑色的', sentence_en: 'I have a black cat.', sentence_zh: '我有一隻黑貓。' },
    { word: 'blue', translation: '藍色的', sentence_en: 'The sky is blue.', sentence_zh: '天空是藍色的。' },
    { word: 'cold', translation: '冷的', sentence_en: 'It is cold today.', sentence_zh: '今天很冷。' },
    { word: 'fast', translation: '快的', sentence_en: 'A cheetah runs very fast.', sentence_zh: '獵豹跑得非常快。' },
    { word: 'good', translation: '好的', sentence_en: 'You are a good student.', sentence_zh: '你是個好學生。' },
    { word: 'green', translation: '綠色的', sentence_en: 'The grass is green.', sentence_zh: '草是綠色的。' },
    { word: 'happy', translation: '快樂的', sentence_en: 'I am very happy.', sentence_zh: '我非常快樂。' },
    { word: 'hot', translation: '熱的', sentence_en: 'The coffee is too hot.', sentence_zh: '這咖啡太燙了。' },
    { word: 'long', translation: '長的', sentence_en: 'She has long hair.', sentence_zh: '她有著長頭髮。' },
    { word: 'many', translation: '很多的', sentence_en: 'I have many friends.', sentence_zh: '我有很多朋友。' },
    { word: 'new', translation: '新的', sentence_en: 'I have a new bike.', sentence_zh: '我有一輛新自行車。' },
    { word: 'old', translation: '老的/舊的', sentence_en: 'My grandfather is old.', sentence_zh: '我的祖父很老了。' },
    { word: 'red', translation: '紅色的', sentence_en: 'An apple is red.', sentence_zh: '蘋果是紅色的。' },
    { word: 'sad', translation: '傷心的', sentence_en: 'Why are you sad?', sentence_zh: '你為什麼傷心？' },
    { word: 'short', translation: '短的/矮的', sentence_en: 'He is short.', sentence_zh: '他很矮。' },
    { word: 'sick', translation: '生病的', sentence_en: 'I feel sick today.', sentence_zh: '我今天覺得不舒服。' },
    { word: 'small', translation: '小的', sentence_en: 'An ant is small.', sentence_zh: '螞蟻很小。' },
    { word: 'warm', translation: '溫暖的', sentence_en: 'The weather is warm.', sentence_zh: '天氣很溫暖。' },
    { word: 'white', translation: '白色的', sentence_en: 'Snow is white.', sentence_zh: '雪是白色的。' },
    { word: 'yellow', translation: '黃色的', sentence_en: 'A banana is yellow.', sentence_zh: '香蕉是黃色的。' },
    { word: 'young', translation: '年輕的', sentence_en: 'My sister is young.', sentence_zh: '我的妹妹很年輕。' },
    { word: 'what', translation: '什麼', sentence_en: 'What is your name?', sentence_zh: '你的名字是什麼？' },
    { word: 'where', translation: '哪裡', sentence_en: 'Where do you live?', sentence_zh: '你住在哪裡？' },
    { word: 'when', translation: '何時', sentence_en: 'When is your birthday?', sentence_zh: '你的生日是什麼時候？' },
    { word: 'why', translation: '為什麼', sentence_en: 'Why are you crying?', sentence_zh: '你為什麼在哭？' },
    { word: 'who', translation: '是誰', sentence_en: 'Who is that man?', sentence_zh: '那個男人是誰？' },
    { word: 'how', translation: '如何', sentence_en: 'How are you?', sentence_zh: '你好嗎？' },
    { word: 'kitchen', translation: '廚房', sentence_en: 'My mother is cooking in the kitchen.', sentence_zh: '我的媽媽正在廚房裡煮飯。' },
    { word: 'library', translation: '圖書館', sentence_en: 'We go to the library to read books.', sentence_zh: '我們去圖書館讀書。' },
    { word: 'mountain', translation: '山', sentence_en: 'That mountain is very high.', sentence_zh: '那座山非常高。' },
    { word: 'river', translation: '河流', sentence_en: 'The fish swims in the river.', sentence_zh: '魚在河裡游泳。' },
    { word: 'ocean', translation: '海洋', sentence_en: 'The ocean is blue and wide.', sentence_zh: '海洋又藍又寬闊。' },
    { word: 'country', translation: '國家/鄉村', sentence_en: 'Japan is a beautiful country.', sentence_zh: '日本是一個美麗的國家。' },
    { word: 'city', translation: '城市', sentence_en: 'Taipei is a big city.', sentence_zh: '台北是一個大城市。' },
    { word: 'garden', translation: '花園', sentence_en: 'There are many flowers in the garden.', sentence_zh: '花園裡有很多花。' },
    { word: 'market', translation: '市場', sentence_en: 'She buys vegetables at the market.', sentence_zh: '她在市場買蔬菜。' },
    { word: 'store', translation: '商店', sentence_en: 'I need to go to the store.', sentence_zh: '我需要去商店。' },
    { word: 'hospital', translation: '醫院', sentence_en: 'The doctor works at the hospital.', sentence_zh: '這位醫生在醫院工作。' },
    { word: 'doctor', translation: '醫生', sentence_en: 'The doctor helped the sick boy.', sentence_zh: '醫生幫助了那個生病的男孩。' },
    { word: 'nurse', translation: '護士', sentence_en: 'The nurse is very kind.', sentence_zh: '那位護士非常親切。' },
    { word: 'teacher', translation: '老師', sentence_en: 'My teacher is Mr. Wang.', sentence_zh: '我的老師是王先生。' },
    { word: 'student', translation: '學生', sentence_en: 'He is a student at my school.', sentence_zh: '他是我學校的學生。' },
    { word: 'family', translation: '家庭', sentence_en: 'I love my family.', sentence_zh: '我愛我的家人。' },
    { word: 'father', translation: '父親', sentence_en: 'My father is tall.', sentence_zh: '我的父親很高。' },
    { word: 'mother', translation: '母親', sentence_en: 'My mother is a teacher.', sentence_zh: '我的母親是一位老師。' },
    { word: 'brother', translation: '兄弟', sentence_en: 'He is my younger brother.', sentence_zh: '他是我弟弟。' },
    { word: 'sister', translation: '姐妹', sentence_en: 'I have one older sister.', sentence_zh: '我有一個姊姊。' },
    { word: 'friend', translation: '朋友', sentence_en: 'You are my best friend.', sentence_zh: '你是我最好的朋友。' },
    { word: 'computer', translation: '電腦', sentence_en: 'I use a computer to study.', sentence_zh: '我用電腦學習。' },
    { word: 'phone', translation: '電話', sentence_en: 'My phone is new.', sentence_zh: '我的手機是新的。' },
    { word: 'music', translation: '音樂', sentence_en: 'I like listening to music.', sentence_zh: '我喜歡聽音樂。' },
    { word: 'movie', translation: '電影', sentence_en: 'Let\'s watch a movie tonight.', sentence_zh: '我們今晚來看電影吧。' },
    { word: 'game', translation: '遊戲', sentence_en: 'They are playing a game.', sentence_zh: '他們正在玩遊戲。' },
    { word: 'sport', translation: '運動', sentence_en: 'Baseball is a popular sport.', sentence_zh: '棒球是一項受歡迎的運動。' },
    { word: 'team', translation: '隊伍', sentence_en: 'We are on the same team.', sentence_zh: '我們在同一隊。' },
    { word: 'fruit', translation: '水果', sentence_en: 'Apple is a kind of fruit.', sentence_zh: '蘋果是一種水果。' },
    { word: 'vegetable', translation: '蔬菜', sentence_en: 'You should eat more vegetables.', sentence_zh: '你應該多吃蔬菜。' },
    { word: 'meat', translation: '肉', sentence_en: 'I don\'t eat meat.', sentence_zh: '我不吃肉。' },
    { word: 'breakfast', translation: '早餐', sentence_en: 'What did you have for breakfast?', sentence_zh: '你早餐吃了什麼？' },
    { word: 'lunch', translation: '午餐', sentence_en: 'It\'s time for lunch.', sentence_zh: '午餐時間到了。' },
    { word: 'dinner', translation: '晚餐', sentence_en: 'Mom is cooking dinner.', sentence_zh: '媽媽正在做晚餐。' },
    { word: 'jacket', translation: '夾克', sentence_en: 'It\'s cold, wear your jacket.', sentence_zh: '天氣冷，穿上你的夾克。' },
    { word: 'shirt', translation: '襯衫', sentence_en: 'He wears a white shirt.', sentence_zh: '他穿著一件白襯衫。' },
    { word: 'pants', translation: '褲子', sentence_en: 'I need a new pair of pants.', sentence_zh: '我需要一條新褲子。' },
    { word: 'socks', translation: '襪子', sentence_en: 'Where are my socks?', sentence_zh: '我的襪子在哪裡？' },
    { word: 'weather', translation: '天氣', sentence_en: 'How is the weather today?', sentence_zh: '今天天氣如何？' },
    { word: 'rain', translation: '雨', sentence_en: 'I don\'t like rain.', sentence_zh: '我不喜歡下雨。' },
    { word: 'snow', translation: '雪', sentence_en: 'Look! It is starting to snow.', sentence_zh: '看！開始下雪了。' },
    { word: 'cloud', translation: '雲', sentence_en: 'The sun is behind the cloud.', sentence_zh: '太陽在雲後面。' },
    { word: 'sky', translation: '天空', sentence_en: 'The sky is clear and blue.', sentence_zh: '天空晴朗且湛藍。' },
    { word: 'road', translation: '路', sentence_en: 'Be careful when you cross the road.', sentence_zh: '過馬路時要小心。' },
    { word: 'street', translation: '街道', sentence_en: 'This street is very busy.', sentence_zh: '這條街很忙碌。' },
    { word: 'bicycle', translation: '自行車', sentence_en: 'I ride my bicycle to school.', sentence_zh: '我騎自行車上學。' },
    { word: 'boat', translation: '船', sentence_en: 'The boat is on the lake.', sentence_zh: '小船在湖上。' },
    { word: 'notebook', translation: '筆記本', sentence_en: 'Write it down in your notebook.', sentence_zh: '把它寫在你的筆記本上。' },
    { word: 'problem', translation: '問題', sentence_en: 'Do you have any problem?', sentence_zh: '你有任何問題嗎？' },
    { word: 'question', translation: '問題', sentence_en: 'May I ask a question?', sentence_zh: '我可以問一個問題嗎？' },
    { word: 'answer', translation: '答案', sentence_en: 'I know the answer.', sentence_zh: '我知道答案。' },
    { word: 'letter', translation: '信/字母', sentence_en: 'I got a letter from my friend.', sentence_zh: '我收到朋友的來信。' },
    { word: 'number', translation: '數字', sentence_en: 'What is your phone number?', sentence_zh: '你的電話號碼是多少？' },
    { word: 'color', translation: '顏色', sentence_en: 'My favorite color is blue.', sentence_zh: '我最喜歡的顏色是藍色。' },
    { word: 'season', translation: '季節', sentence_en: 'There are four seasons in a year.', sentence_zh: '一年有四季。' },
    { word: 'spring', translation: '春天', sentence_en: 'Flowers bloom in spring.', sentence_zh: '春天時花朵盛開。' },
    { word: 'summer', translation: '夏天', sentence_en: 'It\'s very hot in summer.', sentence_zh: '夏天非常熱。' },
    { word: 'fall', translation: '秋天', sentence_en: 'Leaves turn yellow in fall.', sentence_zh: '秋天時葉子變黃。' },
    { word: 'winter', translation: '冬天', sentence_en: 'It snows in winter.', sentence_zh: '冬天下雪。' },
    { word: 'month', translation: '月份', sentence_en: 'January is the first month.', sentence_zh: '一月是第一個月。' },
    { word: 'year', translation: '年', sentence_en: 'Happy New Year!', sentence_zh: '新年快樂！' },
    { word: 'week', translation: '星期', sentence_en: 'There are seven days in a week.', sentence_zh: '一星期有七天。' },
    { word: 'today', translation: '今天', sentence_en: 'What are you going to do today?', sentence_zh: '你今天要做什麼？' },
    { word: 'tomorrow', translation: '明天', sentence_en: 'See you tomorrow.', sentence_zh: '明天見。' },
    { word: 'yesterday', translation: '昨天', sentence_en: 'I was sick yesterday.', sentence_zh: '我昨天生病了。' },
    { word: 'clock', translation: '時鐘', sentence_en: 'The clock is on the wall.', sentence_zh: '時鐘在牆上。' },
    { word: 'watch', translation: '手錶', sentence_en: 'He has a new watch.', sentence_zh: '他有了一隻新錶。' },
    { word: 'class', translation: '課程/班級', sentence_en: 'I have an English class at 10.', sentence_zh: '我十點有英文課。' },
    { word: 'room', translation: '房間', sentence_en: 'This is my room.', sentence_zh: '這是我的房間。' },
    { word: 'classroom', translation: '教室', sentence_en: 'The students are in the classroom.', sentence_zh: '學生們在教室裡。' },
    { word: 'park', translation: '公園', sentence_en: 'We play in the park.', sentence_zh: '我們在公園裡玩。' },
    { word: 'farm', translation: '農場', sentence_en: 'There are many animals on the farm.', sentence_zh: '農場裡有很多動物。' },
    { word: 'bank', translation: '銀行', sentence_en: 'I need to go to the bank.', sentence_zh: '我需要去銀行。' },
    { word: 'station', translation: '車站', sentence_en: 'Let\'s meet at the train station.', sentence_zh: '我們在火車站見。' },
    { word: 'ground', translation: '地面', sentence_en: 'Don\'t sit on the ground.', sentence_zh: '不要坐在地上。' },
    { word: 'floor', translation: '地板/樓層', sentence_en: 'My room is on the second floor.', sentence_zh: '我的房間在二樓。' },
    { word: 'wall', translation: '牆壁', sentence_en: 'There is a picture on the wall.', sentence_zh: '牆上有一幅畫。' },
    { word: 'paper', translation: '紙', sentence_en: 'Give me a piece of paper.', sentence_zh: '給我一張紙。' },
    { word: 'fire', translation: '火', sentence_en: 'Fire is dangerous.', sentence_zh: '火很危險。' },
    { word: 'wind', translation: '風', sentence_en: 'The wind is strong today.', sentence_zh: '今天的風很強。' },
    { word: 'air', translation: '空氣', sentence_en: 'We need clean air to breathe.', sentence_zh: '我們需要乾淨的空氣來呼吸。' },
    { word: 'story', translation: '故事', sentence_en: 'My mom reads me a story.', sentence_zh: '我媽媽讀故事給我聽。' },
    { word: 'picture', translation: '圖片/畫', sentence_en: 'He drew a picture of a cat.', sentence_zh: '他畫了一張貓的圖。' },
    { word: 'animal', translation: '動物', sentence_en: 'A lion is a wild animal.', sentence_zh: '獅子是野生動物。' },
    { word: 'plant', translation: '植物', sentence_en: 'Plants need water and sun.', sentence_zh: '植物需要水和陽光。' },
    { word: 'body', translation: '身體', sentence_en: 'Exercise is good for your body.', sentence_zh: '運動對你的身體有益。' },
    { word: 'hair', translation: '頭髮', sentence_en: 'She has long black hair.', sentence_zh: '她有著長長的黑髮。' },
    { word: 'ear', translation: '耳朵', sentence_en: 'We hear with our ears.', sentence_zh: '我們用耳朵聽。' },
    { word: 'mouth', translation: '嘴巴', sentence_en: 'Open your mouth and say "Ah".', sentence_zh: '張開你的嘴說「啊」。' },
    { word: 'tooth', translation: '牙齒', sentence_en: 'Brush your teeth every day.', sentence_zh: '每天刷牙。' },
    { word: 'back', translation: '背部', sentence_en: 'My back hurts.', sentence_zh: '我的背很痛。' },
    { word: 'finger', translation: '手指', sentence_en: 'You have five fingers on one hand.', sentence_zh: '你一隻手有五根手指。' },
    { word: 'agree', translation: '同意', sentence_en: 'I agree with you.', sentence_zh: '我同意你的看法。' },
    { word: 'believe', translation: '相信', sentence_en: 'Do you believe in ghosts?', sentence_zh: '你相信有鬼嗎？' },
    { word: 'borrow', translation: '借(入)', sentence_en: 'Can I borrow your pencil?', sentence_zh: '我可以借你的鉛筆嗎？' },
    { word: 'bring', translation: '帶來', sentence_en: 'Please bring your homework tomorrow.', sentence_zh: '請明天帶你的作業來。' },
    { word: 'build', translation: '建造', sentence_en: 'They are building a new house.', sentence_zh: '他們正在蓋新房子。' },
    { word: 'buy', translation: '買', sentence_en: 'I want to buy a new shirt.', sentence_zh: '我想買一件新襯衫。' },
    { word: 'call', translation: '打電話/稱呼', sentence_en: 'Call me later.', sentence_zh: '待會打給我。' },
    { word: 'change', translation: '改變', sentence_en: 'People change, but the city stays the same.', sentence_zh: '人會變，但城市依舊。' },
    { word: 'clean', translation: '打掃', sentence_en: 'Please clean your room.', sentence_zh: '請打掃你的房間。' },
    { word: 'climb', translation: '爬', sentence_en: 'The monkey can climb the tree.', sentence_zh: '猴子會爬樹。' },
    { word: 'cook', translation: '煮飯', sentence_en: 'My father likes to cook.', sentence_zh: '我爸爸喜歡做飯。' },
    { word: 'count', translation: '數', sentence_en: 'Can you count from one to ten?', sentence_zh: '你會從一數到十嗎？' },
    { word: 'cry', translation: '哭', sentence_en: 'The baby is crying.', sentence_zh: '寶寶在哭。' },
    { word: 'cut', translation: '切', sentence_en: 'Be careful when you cut the paper.', sentence_zh: '你剪紙的時候要小心。' },
    { word: 'dance', translation: '跳舞', sentence_en: 'She likes to dance.', sentence_zh: '她喜歡跳舞。' },
    { word: 'decide', translation: '決定', sentence_en: 'I can\'t decide what to eat.', sentence_zh: '我無法決定要吃什麼。' },
    { word: 'drive', translation: '開車', sentence_en: 'My brother can drive a car.', sentence_zh: '我哥哥會開車。' },
    { word: 'enjoy', translation: '享受', sentence_en: 'I enjoy reading.', sentence_zh: '我享受閱讀。' },
    { word: 'explain', translation: '解釋', sentence_en: 'Can you explain this word to me?', sentence_zh: '你能跟我解釋這個字嗎？' },
    { word: 'fall', translation: '掉落/跌倒', sentence_en: 'Leaves fall in autumn.', sentence_zh: '葉子在秋天掉落。' },
    { word: 'feel', translation: '感覺', sentence_en: 'How do you feel today?', sentence_zh: '你今天覺得如何？' },
    { word: 'find', translation: '找到', sentence_en: 'I can\'t find my keys.', sentence_zh: '我找不到我的鑰匙。' },
    { word: 'finish', translation: '完成', sentence_en: 'Have you finished your homework?', sentence_zh: '你完成你的作業了嗎？' },
    { word: 'follow', translation: '跟隨', sentence_en: 'Follow me, please.', sentence_zh: '請跟我來。' },
    { word: 'forget', translation: '忘記', sentence_en: 'Don\'t forget to close the door.', sentence_zh: '不要忘記關門。' },
    { word: 'guess', translation: '猜', sentence_en: 'Guess what I have in my hand?', sentence_zh: '猜猜我手裡有什麼？' },
    { word: 'happen', translation: '發生', sentence_en: 'What happened?', sentence_zh: '發生什麼事了？' },
    { word: 'hear', translation: '聽到', sentence_en: 'I can hear music.', sentence_zh: '我能聽到音樂。' },
    { word: 'hope', translation: '希望', sentence_en: 'I hope it doesn\'t rain tomorrow.', sentence_zh: '我希望明天不要下雨。' },
    { word: 'invite', translation: '邀請', sentence_en: 'He invited me to his party.', sentence_zh: '他邀請我參加他的派對。' },
    { word: 'join', translation: '參加/加入', sentence_en: 'Do you want to join us?', sentence_zh: '你想加入我們嗎？' },
    { word: 'keep', translation: '保持', sentence_en: 'Please keep quiet.', sentence_zh: '請保持安靜。' },
    { word: 'laugh', translation: '笑', sentence_en: 'That story makes me laugh.', sentence_zh: '那個故事讓我發笑。' },
    { word: 'learn', translation: '學習', sentence_en: 'We learn new things at school.', sentence_zh: '我們在學校學習新事物。' },
    { word: 'leave', translation: '離開', sentence_en: 'The train will leave at 3 PM.', sentence_zh: '火車將在下午三點離開。' },
    { word: 'lend', translation: '借(出)', sentence_en: 'Can you lend me some money?', sentence_zh: '你可以借我一些錢嗎？' },
    { word: 'lose', translation: '失去/輸', sentence_en: 'I don\'t want to lose the game.', sentence_zh: '我不想輸掉比賽。' },
    { word: 'meet', translation: '遇見', sentence_en: 'Nice to meet you.', sentence_zh: '很高興認識你。' },
    { word: 'move', translation: '移動', sentence_en: 'Can you move this box?', sentence_zh: '你能移動這個箱子嗎？' },
    { word: 'need', translation: '需要', sentence_en: 'I need your help.', sentence_zh: '我需要你的幫忙。' },
    { word: 'paint', translation: '畫畫/油漆', sentence_en: 'He is painting a picture.', sentence_zh: '他正在畫一幅畫。' },
    { word: 'pass', translation: '通過/傳遞', sentence_en: 'Please pass me the salt.', sentence_zh: '請把鹽遞給我。' },
    { word: 'pay', translation: '付錢', sentence_en: 'I need to pay the bill.', sentence_zh: '我需要付帳單。' },
    { word: 'practice', translation: '練習', sentence_en: 'You need to practice every day.', sentence_zh: '你需要每天練習。' },
    { word: 'pull', translation: '拉', sentence_en: 'Pull the door to open it.', sentence_zh: '拉開門。' },
    { word: 'push', translation: '推', sentence_en: 'Push the door to close it.', sentence_zh: '推上門。' },
    { word: 'remember', translation: '記得', sentence_en: 'I remember your name.', sentence_zh: '我記得你的名字。' },
    { word: 'sell', translation: '賣', sentence_en: 'He sells fruit at the market.', sentence_zh: '他在市場賣水果。' },
    { word: 'send', translation: '寄送', sentence_en: 'I will send you a postcard.', sentence_zh: '我會寄明信片給你。' },
    { word: 'show', translation: '展示', sentence_en: 'Show me your new book.', sentence_zh: '給我看你的新書。' },
    { word: 'smell', translation: '聞', sentence_en: 'The flower smells good.', sentence_zh: '這花聞起來很香。' },
    { word: 'smile', translation: '微笑', sentence_en: 'She has a beautiful smile.', sentence_zh: '她有著美麗的微笑。' },
    { word: 'start', translation: '開始', sentence_en: 'The class starts at 9 AM.', sentence_zh: '課程在早上九點開始。' },
    { word: 'stop', translation: '停止', sentence_en: 'Please stop talking.', sentence_zh: '請停止說話。' },
    { word: 'taste', translation: '嚐', sentence_en: 'Taste the soup, it\'s delicious.', sentence_zh: '嚐嚐這湯，它很美味。' },
    { word: 'touch', translation: '觸摸', sentence_en: 'Don\'t touch the painting.', sentence_zh: '請勿觸摸畫作。' },
    { word: 'try', translation: '嘗試', sentence_en: 'Let\'s try again.', sentence_zh: '我們再試一次吧。' },
    { word: 'turn', translation: '轉動', sentence_en: 'Turn left at the corner.', sentence_zh: '在轉角處左轉。' },
    { word: 'understand', translation: '理解', sentence_en: 'I don\'t understand this question.', sentence_zh: '我不懂這個問題。' },
    { word: 'visit', translation: '拜訪', sentence_en: 'I will visit my grandparents this weekend.', sentence_zh: '我這週末會去拜訪我的祖父母。' },
    { word: 'wait', translation: '等待', sentence_en: 'Please wait for me.', sentence_zh: '請等等我。' },
    { word: 'wake', translation: '醒來', sentence_en: 'I wake up at 6 AM every day.', sentence_zh: '我每天早上六點起床。' },
    { word: 'wash', translation: '洗', sentence_en: 'He is washing his car.', sentence_zh: '他正在洗他的車。' },
    { word: 'win', translation: '贏', sentence_en: 'I hope our team will win.', sentence_zh: '我希望我們隊能贏。' },
    { word: 'worry', translation: '擔心', sentence_en: 'Don\'t worry, be happy.', sentence_zh: '別擔心，開心點。' },
    { word: 'beautiful', translation: '美麗的', sentence_en: 'She is a beautiful girl.', sentence_zh: '她是個美麗的女孩。' },
    { word: 'brave', translation: '勇敢的', sentence_en: 'The firefighter is very brave.', sentence_zh: '那位消防員非常勇敢。' },
    { word: 'busy', translation: '忙碌的', sentence_en: 'My father is always busy.', sentence_zh: '我爸爸總是很忙。' },
    { word: 'careful', translation: '小心的', sentence_en: 'Please be careful.', sentence_zh: '請小心。' },
    { word: 'clever', translation: '聰明的', sentence_en: 'He is a clever student.', sentence_zh: '他是個聰明的學生。' },
    { word: 'dangerous', translation: '危險的', sentence_en: 'It is dangerous to play with fire.', sentence_zh: '玩火是危險的。' },
    { word: 'dark', translation: '黑暗的', sentence_en: 'It\'s too dark to read.', sentence_zh: '太暗了無法閱讀。' },
    { word: 'different', translation: '不同的', sentence_en: 'My brother and I have different hobbies.', sentence_zh: '我哥和我有不同的愛好。' },
    { word: 'difficult', translation: '困難的', sentence_en: 'This math problem is difficult.', sentence_zh: '這道數學題很難。' },
    { word: 'dirty', translation: '骯髒的', sentence_en: 'Your hands are dirty.', sentence_zh: '你的手很髒。' },
    { word: 'dry', translation: '乾燥的', sentence_en: 'My clothes are not dry yet.', sentence_zh: '我的衣服還沒乾。' },
    { word: 'early', translation: '早的', sentence_en: 'I get up early every morning.', sentence_zh: '我每天都很早起床。' },
    { word: 'easy', translation: '簡單的', sentence_en: 'The test was very easy.', sentence_zh: '這次考試很簡單。' },
    { word: 'expensive', translation: '昂貴的', sentence_en: 'This watch is too expensive.', sentence_zh: '這隻手錶太貴了。' },
    { word: 'famous', translation: '有名的', sentence_en: 'He is a famous singer.', sentence_zh: '他是一位有名的歌手。' },
    { word: 'far', translation: '遠的', sentence_en: 'The school is far from my home.', sentence_zh: '學校離我家很遠。' },
    { word: 'fine', translation: '好的', sentence_en: 'I am fine, thank you.', sentence_zh: '我很好，謝謝你。' },
    { word: 'free', translation: '空閒的/免費的', sentence_en: 'Are you free this afternoon?', sentence_zh: '你今天下午有空嗎？' },
    { word: 'fresh', translation: '新鮮的', sentence_en: 'I like fresh fruit.', sentence_zh: '我喜歡新鮮的水果。' },
    { word: 'full', translation: '滿的', sentence_en: 'The glass is full of water.', sentence_zh: '杯子裡裝滿了水。' },
    { word: 'heavy', translation: '重的', sentence_en: 'The box is very heavy.', sentence_zh: '這個箱子很重。' },
    { word: 'high', translation: '高的', sentence_en: 'The mountain is very high.', sentence_zh: '這座山非常高。' },
    { word: 'important', translation: '重要的', sentence_en: 'Health is very important.', sentence_zh: '健康非常重要。' },
    { word: 'interesting', translation: '有趣的', sentence_en: 'This book is very interesting.', sentence_zh: '這本書非常有趣。' },
    { word: 'kind', translation: '親切的', sentence_en: 'Thank you, you are very kind.', sentence_zh: '謝謝你，你人真好。' },
    { word: 'large', translation: '大的', sentence_en: 'We live in a large house.', sentence_zh: '我們住在一間大房子裡。' },
    { word: 'late', translation: '晚的/遲的', sentence_en: 'Don\'t be late for school.', sentence_zh: '上學不要遲到。' },
    { word: 'light', translation: '輕的/亮的', sentence_en: 'This bag is very light.', sentence_zh: '這個袋子很輕。' },
    { word: 'little', translation: '小的/少的', sentence_en: 'I have a little dog.', sentence_zh: '我有一隻小狗。' },
    { word: 'loud', translation: '大聲的', sentence_en: 'The music is too loud.', sentence_zh: '音樂太大聲了。' },
    { word: 'lucky', translation: '幸運的', sentence_en: 'Today is my lucky day.', sentence_zh: '今天E是我的幸運日。' },
    { word: 'near', translation: '近的', sentence_en: 'My home is near the school.', sentence_zh: '我家離學校很近。' },
    { word: 'poor', translation: '貧窮的', sentence_en: 'He is poor, but he is happy.', sentence_zh: '他很窮，但是他很快樂。' },
    { word: 'pretty', translation: '漂亮的', sentence_en: 'What a pretty flower!', sentence_zh: '多麼漂亮的花啊！' },
    { word: 'quick', translation: '快的', sentence_en: 'Please give me a quick answer.', sentence_zh: '請盡快給我答覆。' },
    { word: 'quiet', translation: '安靜的', sentence_en: 'Please be quiet in the library.', sentence_zh: '在圖書館請保持安靜。' },
    { word: 'ready', translation: '準備好的', sentence_en: 'Are you ready to go?', sentence_zh: '你準備好要走了嗎？' },
    { word: 'rich', translation: '富有的', sentence_en: 'He is a very rich man.', sentence_zh: '他是個非常有錢的人。' },
    { word: 'right', translation: '對的/右邊的', sentence_en: 'That is the right answer.', sentence_zh: '那是正確答案。' },
    { word: 'safe', translation: '安全的', sentence_en: 'It is not safe to swim here.', sentence_zh: '在這裡游泳不安全。' },
    { word: 'same', translation: '相同的', sentence_en: 'We are in the same class.', sentence_zh: '我們在同一個班級。' },
    { word: 'serious', translation: '嚴肅的/嚴重的', sentence_en: 'He is a serious student.', sentence_zh: '他是個認真的學生。' },
    { word: 'slow', translation: '慢的', sentence_en: 'A turtle walks very slow.', sentence_zh: '烏龜走得很慢。' },
    { word: 'strong', translation: '強壯的', sentence_en: 'My father is very strong.', sentence_zh: '我爸爸非常強壯。' },
    { word: 'sure', translation: '確定的', sentence_en: 'Are you sure?', sentence_zh: '你確定嗎？' },
    { word: 'sweet', translation: '甜的', sentence_en: 'This cake is too sweet.', sentence_zh: '這個蛋糕太甜了。' },
    { word: 'tall', translation: '高的', sentence_en: 'He is taller than me.', sentence_zh: '他比我高。' },
    { word: 'thin', translation: '瘦的/薄的', sentence_en: 'She is very thin.', sentence_zh: '她非常瘦。' },
    { word: 'tired', translation: '疲累的', sentence_en: 'I am so tired.', sentence_zh: '我好累。' },
    { word: 'useful', translation: '有用的', sentence_en: 'This tool is very useful.', sentence_zh: '這個工具非常有用。' },
    { word: 'wet', translation: '濕的', sentence_en: 'My clothes are all wet.', sentence_zh: '我的衣服全都濕了。' },
    { word: 'wide', translation: '寬的', sentence_en: 'The river is very wide.', sentence_zh: '這條河非常寬。' },
    { word: 'windy', translation: '風大的', sentence_en: 'It\'s a windy day.', sentence_zh: '今天是風大的一天。' },
    { word: 'wrong', translation: '錯的', sentence_en: 'This answer is wrong.', sentence_zh: '这个答案是錯的。' },
    { word: 'always', translation: '總是', sentence_en: 'He always gets up early.', sentence_zh: '他總是早起。' },
    { word: 'never', translation: '從不', sentence_en: 'I never eat breakfast.', sentence_zh: '我從來不吃早餐。' },
    { word: 'often', translation: '時常', sentence_en: 'I often go to the park.', sentence_zh: '我時常去公園。' },
    { word: 'sometimes', translation: '有時候', sentence_en: 'Sometimes I feel sad.', sentence_zh: '有時候我感到難過。' },
    { word: 'usually', translation: '通常', sentence_en: 'I usually walk to school.', sentence_zh: '我通常走路去上學。' },
    { word: 'now', translation: '現在', sentence_en: 'I am busy now.', sentence_zh: '我現在很忙。' },
    { word: 'then', translation: '然後', sentence_en: 'I finished my homework, and then I watched TV.', sentence_zh: '我寫完作業，然後就去看電視了。' },
    { word: 'here', translation: '這裡', sentence_en: 'Please come here.', sentence_zh: '請來這裡。' },
    { word: 'there', translation: '那裡', sentence_en: 'The book is over there.', sentence_zh: '書在那裡。' },
    { word: 'very', translation: '非常', sentence_en: 'It is very hot.', sentence_zh: '天氣非常熱。' },
    { word: 'too', translation: '太', sentence_en: 'This is too difficult.', sentence_zh: '這太難了。' },
    { word: 'also', translation: '也', sentence_en: 'I also like ice cream.', sentence_zh: '我也喜歡冰淇淋。' },
    { word: 'just', translation: '只是/剛才', sentence_en: 'He just left.', sentence_zh: '他剛離開。' },
    { word: 'only', translation: '只有', sentence_en: 'I have only one dollar.', sentence_zh: '我只有一塊錢。' },
    { word: 'again', translation: '再一次', sentence_en: 'Please say it again.', sentence_zh: '請再說一次。' },
    { word: 'first', translation: '第一', sentence_en: 'He is the first to arrive.', sentence_zh: '他是第一個到的。' },
    { word: 'last', translation: '最後的', sentence_en: 'This is the last chance.', sentence_zh: '這是最後的機會。' },
    { word: 'Monday', translation: '星期一', sentence_en: 'Today is Monday.', sentence_zh: '今天是星期一。' },
    { word: 'Tuesday', translation: '星期二', sentence_en: 'We have PE class on Tuesday.', sentence_zh: '我們星期二有體育課。' },
    { word: 'Wednesday', translation: '星期三', sentence_en: 'Wednesday is the middle of the week.', sentence_zh: '星期三是一週的中間。' },
    { word: 'Thursday', translation: '星期四', sentence_en: 'I have a test on Thursday.', sentence_zh: '我星期四有考試。' },
    { word: 'Friday', translation: '星期五', sentence_en: 'I love Friday!', sentence_zh: '我愛星期五！' },
    { word: 'Saturday', translation: '星期六', sentence_en: 'Let\'s go hiking on Saturday.', sentence_zh: '我們星期六去健行吧。' },
    { word: 'Sunday', translation: '星期日', sentence_en: 'Sunday is a day of rest.', sentence_zh: '星期日是休息的日子。' },
    { word: 'January', translation: '一月', sentence_en: 'My birthday is in January.', sentence_zh: '我的生日在一月。' },
    { word: 'February', translation: '二月', sentence_en: 'February is the shortest month.', sentence_zh: '二月是最短的月份。' },
    { word: 'March', translation: '三月', sentence_en: 'Spring begins in March.', sentence_zh: '春天從三月開始。' },
    { word: 'April', translation: '四月', sentence_en: 'April showers bring May flowers.', sentence_zh: '四月的陣雨帶來五月的花朵。' },
    { word: 'May', translation: '五月', sentence_en: 'My mother\'s birthday is in May.', sentence_zh: '我媽媽的生日在五月。' },
    { word: 'June', translation: '六月', sentence_en: 'Summer starts in June.', sentence_zh: '夏天從六月開始。' },
    { word: 'July', translation: '七月', sentence_en: 'July is often very hot.', sentence_zh: '七月通常很熱。' },
    { word: 'August', translation: '八月', sentence_en: 'We have summer vacation in August.', sentence_zh: '我們八月放暑假。' },
    { word: 'September', translation: '九月', sentence_en: 'School starts in September.', sentence_zh: '九月開學。' },
    { word: 'October', translation: '十月', sentence_en: 'Halloween is in October.', sentence_zh: '萬聖節在十月。' },
    { word: 'November', translation: '十一月', sentence_en: 'Thanksgiving is in November.', sentence_zh: '感恩節在十一月。' },
    { word: 'December', translation: '十二月', sentence_en: 'Christmas is in December.', sentence_zh: '聖誕節在十二月。' },
    { word: 'hundred', translation: '百', sentence_en: 'There are one hundred students.', sentence_zh: '這裡有一百個學生。' },
    { word: 'thousand', translation: '千', sentence_en: 'It costs one thousand dollars.', sentence_zh: '這個要一千元。' },
    { word: 'million', translation: '百萬', sentence_en: 'He won a million dollars.', sentence_zh: '他贏了一百萬元。' },
    { word: 'address', translation: '地址', sentence_en: 'What is your address?', sentence_zh: '你的地址是什麼？' },
    { word: 'age', translation: '年齡', sentence_en: 'What is your age?', sentence_zh: '你幾歲？' },
    { word: 'art', translation: '藝術', sentence_en: 'I like art class.', sentence_zh: '我喜歡美術課。' },
    { word: 'beach', translation: '海灘', sentence_en: 'Let\'s go to the beach.', sentence_zh: '我們去海灘吧。' },
    { word: 'camera', translation: '相機', sentence_en: 'She took a photo with her camera.', sentence_zh: '她用她的相機拍了張照。' },
    { word: 'chicken', translation: '雞', sentence_en: 'I like to eat fried chicken.', sentence_zh: '我喜歡吃炸雞。' },
    { word: 'child', translation: '小孩', sentence_en: 'He is just a child.', sentence_zh: '他只個一個孩子。' },
    { word: 'church', translation: '教堂', sentence_en: 'They go to church on Sunday.', sentence_zh: '他們星期天去教堂。' },
    { word: 'circle', translation: '圓形', sentence_en: 'Draw a circle.', sentence_zh: '畫一個圓形。' },
    { word: 'coat', translation: '外套', sentence_en: 'Put on your coat, it\'s cold.', sentence_zh: '穿上外套，外面很冷。' },
    { word: 'coffee', translation: '咖啡', sentence_en: 'My father drinks coffee every morning.', sentence_zh: '我爸爸每天早上都喝咖啡。' },
    { word: 'cookie', translation: '餅乾', sentence_en: 'I want a chocolate cookie.', sentence_zh: '我想要一塊巧克力餅乾。' },
    { word: 'corner', translation: '角落', sentence_en: 'The shop is on the corner.', sentence_zh: '那間店在轉角。' },
    { word: 'date', translation: '日期', sentence_en: 'What\'s the date today?', sentence_zh: '今天幾號？' },
    { word: 'dream', translation: '夢', sentence_en: 'I had a strange dream last night.', sentence_zh: '我昨晚做了一個奇怪的夢。' },
    { word: 'dress', translation: '洋裝', sentence_en: 'She is wearing a beautiful dress.', sentence_zh: '她穿著一件漂亮的洋裝。' },
    { word: 'farmer', translation: '農夫', sentence_en: 'The farmer works on the farm.', sentence_zh: '農夫在農場工作。' },
    { word: 'gift', translation: '禮物', sentence_en: 'This is a gift for you.', sentence_zh: '這是給你的禮物。' },
    { word: 'grape', translation: '葡萄', sentence_en: 'Grapes are my favorite fruit.', sentence_zh: '葡萄是我最愛的水果。' },
    { word: 'grass', translation: '草', sentence_en: 'The grass is green.', sentence_zh: '草是綠色的。' },
    { word: 'hobby', translation: '愛好', sentence_en: 'My hobby is reading.', sentence_zh: '我的愛好是閱讀。' },
    { word: 'holiday', translation: '假日', sentence_en: 'Tomorrow is a holiday.', sentence_zh: '明天是假日。' },
    { word: 'idea', translation: '點子', sentence_en: 'That\'s a good idea!', sentence_zh: '真是個好主意！' },
    { word: 'island', translation: '島嶼', sentence_en: 'Taiwan is a beautiful island.', sentence_zh: '台灣是個美麗的島嶼。' },
    { word: 'job', translation: '工作', sentence_en: 'He is looking for a new job.', sentence_zh: '他正在找新工作。' },
    { word: 'juice', translation: '果汁', sentence_en: 'I want a glass of orange juice.', sentence_zh: '我想要一杯柳橙汁。' },
    { word: 'lake', translation: '湖', sentence_en: 'We went boating on the lake.', sentence_zh: '我們去湖上划船。' },
    { word: 'light', translation: '光/燈', sentence_en: 'Please turn on the light.', sentence_zh: '請開燈。' },
    { word: 'magic', translation: '魔術', sentence_en: 'He showed me a magic trick.', sentence_zh: '他秀了一個魔術戲法給我看。' },
    { word: 'meal', translation: '餐', sentence_en: 'We have three meals a day.', sentence_zh: '我們一天吃三餐。' },
    { word: 'message', translation: '訊息', sentence_en: 'I sent you a message.', sentence_zh: '我寄了一個訊息給你。' },
    { word: 'mistake', translation: '錯誤', sentence_en: 'I made a mistake.', sentence_zh: '我犯了一個錯。' },
    { word: 'party', translation: '派對', sentence_en: 'Are you going to the party?', sentence_zh: '你會去那個派對嗎？' },
    { word: 'place', translation: '地方', sentence_en: 'This is a good place for a picnic.', sentence_zh: '這裡是個野餐的好地方。' },
    { word: 'price', translation: '價格', sentence_en: 'What is the price of this book?', sentence_zh: '這本書的價格是多少？' },
    { word: 'queen', translation: '女王', sentence_en: 'The Queen lives in the palace.', sentence_zh: '女王住在皇宮裡。' },
    { word: 'king', translation: '國王', sentence_en: 'The king is very powerful.', sentence_zh: '國王非常強大。' },
    { word: 'restroom', translation: '廁所', sentence_en: 'May I go to the restroom?', sentence_zh: '我可以去廁所嗎？' },
    { word: 'sea', translation: '海', sentence_en: 'We can see the sea from here.', sentence_zh: '我們可以從這裡看到海。' },
    { word: 'seat', translation: '座位', sentence_en: 'Please take your seat.', sentence_zh: '請就座。' },
    { word: 'side', translation: '邊', sentence_en: 'Please stand on this side.', sentence_zh: '請站在這邊。' },
    { word: 'size', translation: '尺寸', sentence_en: 'What size do you wear?', sentence_zh: '你穿什麼尺寸？' },
    { word: 'snake', translation: '蛇', sentence_en: 'I am afraid of snakes.', sentence_zh: '我怕蛇。' },
    { word: 'sound', translation: '聲音', sentence_en: 'I heard a strange sound.', sentence_zh: '我聽到一個奇怪的聲音。' },
    { word: 'stamp', translation: '郵票', sentence_en: 'I need a stamp for this letter.', sentence_zh: '這封信我需要一張郵票。' },
    { word: 'subject', translation: '科目', sentence_en: 'What is your favorite subject?', sentence_zh: '你最喜歡的科目是什麼？' },
    { word: 'taxi', translation: '計程車', sentence_en: 'Let\'s take a taxi.', sentence_zh: '我們搭計程車吧。' },
    { word: 'ticket', translation: '票', sentence_en: 'I bought a ticket for the movie.', sentence_zh: '我買了一張電影票。' },
    { word: 'tiger', translation: '老虎', sentence_en: 'A tiger is a big cat.', sentence_zh: '老虎是一種大貓。' },
    { word: 'toast', translation: '吐司', sentence_en: 'I like toast with butter.', sentence_zh: '我喜歡塗奶油的吐司。' },
    { word: 'town', translation: '城鎮', sentence_en: 'I live in a small town.', sentence_zh: '我住在一個小鎮上。' },
    { word: 'traffic', translation: '交通', sentence_en: 'The traffic is heavy in the morning.', sentence_zh: '早上的交通很壅塞。' },
    { word: 'trip', translation: '旅行', sentence_en: 'We had a good trip.', sentence_zh: '我們有趟愉快的旅行。' },
    { word: 'uncle', translation: '叔叔/伯伯', sentence_en: 'My uncle lives in Taipei.', sentence_zh: '我的叔叔住在台北。' },
    { word: 'aunt', translation: '阿姨/姑姑', sentence_en: 'My aunt is very nice.', sentence_zh: '我的阿姨人很好。' },
    { word: 'vacation', translation: '假期', sentence_en: 'What will you do during summer vacation?', sentence_zh: '暑假期間你打算做什麼？' },
    { word: 'voice', translation: '聲音(人聲)', sentence_en: 'She has a beautiful voice.', sentence_zh: '她的聲音很美。' },
    { word: 'above', translation: '在...之上', sentence_en: 'The sky is above us.', sentence_zh: '天空在我們之上。' },
    { word: 'across', translation: '穿過', sentence_en: 'He walked across the street.', sentence_zh: '他穿過街道。' },
    { word: 'after', translation: '在...之後', sentence_en: 'I will call you after lunch.', sentence_zh: '我午餐後會打給你。' },
    { word: 'around', translation: '圍繞/大約', sentence_en: 'He walked around the lake.', sentence_zh: '他繞著湖走。' },
    { word: 'before', translation: '在...之前', sentence_en: 'Brush your teeth before bed.', sentence_zh: '睡前刷牙。' },
    { word: 'behind', translation: '在...後面', sentence_en: 'The cat is behind the tree.', sentence_zh: '貓在樹後面。' },
    { word: 'between', translation: '在...之間', sentence_en: 'I sit between my two friends.', sentence_zh: '我坐在我的兩個朋友中間。' },
    { word: 'down', translation: '向下', sentence_en: 'Please sit down.', sentence_zh: '請坐下。' },
    { word: 'from', translation: '從', sentence_en: 'I am from Taiwan.', sentence_zh: '我來自台灣。' },
    { word: 'in', translation: '在...裡面', sentence_en: 'The keys are in the box.', sentence_zh: '鑰匙在盒子裡。' },
    { word: 'into', translation: '進入', sentence_en: 'He jumped into the river.', sentence_zh: '他跳進了河裡。' },
    { word: 'near', translation: '靠近', sentence_en: 'My house is near the park.', sentence_zh: '我家靠近公園。' },
    { word: 'next', translation: '下一個/旁邊', sentence_en: 'She is sitting next to me.', sentence_zh: '她坐在我旁邊。' },
    { word: 'on', translation: '在...上面', sentence_en: 'The book is on the table.', sentence_zh: '書在桌上。' },
    { word: 'over', translation: '在...上方/越過', sentence_en: 'The bird flew over the house.', sentence_zh: '鳥飛過了房子。' },
    { word: 'through', translation: '穿過', sentence_en: 'We walked through the forest.', sentence_zh: '我們步行穿過森林。' },
    { word: 'to', translation: '到', sentence_en: 'I go to school every day.', sentence_zh: '我每天都去學校。' },
    { word: 'under', translation: '在...下面', sentence_en: 'The cat is under the table.', sentence_zh: '貓在桌子下面。' },
    { word: 'up', translation: '向上', sentence_en: 'Look up at the sky.', sentence_zh: '抬頭看看天空。' },
    { word: 'with', translation: '和...一起', sentence_en: 'I live with my family.', sentence_zh: '我和我的家人住在一起。' },
    { word: 'without', translation: '沒有', sentence_en: 'I can\'t live without you.', sentence_zh: '我沒有你活不下去。' },
    { word: 'about', translation: '關於', sentence_en: 'This book is about animals.', sentence_zh: '這本書是關於動物的。' },
    { word: 'at', translation: '在(地點/時間)', sentence_en: 'I will meet you at the station.', sentence_zh: '我會在車站跟你見面。' },
    { word: 'by', translation: '藉由/在旁邊', sentence_en: 'He goes to work by bus.', sentence_zh: '他搭公車上班。' },
    { word: 'for', translation: '為了', sentence_en: 'This gift is for you.', sentence_zh: '這個禮物是給你的。' },
    { word: 'of', translation: '...的', sentence_en: 'He is a friend of mine.', sentence_zh: '他是我的一個朋友。' },
    { word: 'or', translation: '或者', sentence_en: 'Do you want tea or coffee?', sentence_zh: '你想要茶還是咖啡？' },
    { word: 'but', translation: '但是', sentence_en: 'I am tired, but I have to work.', sentence_zh: '我很累，但我必須工作。' },
    { word: 'so', translation: '所以', sentence_en: 'It was raining, so I took an umbrella.', sentence_zh: '因為下雨了，所以我帶了傘。' }
];